# Generated by Django 5.2.4 on 2026-08-02 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Info'), ('MEDIUM', 'Important'), ('HIGH', 'Urgent')], default='LOW', max_length=10)),
                ('is_public', models.BooleanField(default=True, help_text='Show on public result page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('ON', 'On-Campus'), ('OFF', 'Off-Campus'), ('BOTH', 'Combined On & Off-Campus')], default='ON', max_length=10)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.competition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_no', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('total_points', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='core.category')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='core.competition')),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
            options={
                'ordering': ['chest_no'],
            },
        ),
        migrations.CreateModel(
            name='FestDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(default='09:00', help_text='Operating start time')),
                ('end_time', models.TimeField(default='21:00', help_text='Operating end time')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fest_days', to='core.competition')),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_1_points', models.IntegerField(default=10)),
                ('rank_2_points', models.IntegerField(default=6)),
                ('rank_3_points', models.IntegerField(default=3)),
                ('grade_a_points', models.IntegerField(default=10)),
                ('grade_b_points', models.IntegerField(default=6)),
                ('grade_c_points', models.IntegerField(default=3)),
                ('grade_a_threshold', models.IntegerField(default=80)),
                ('grade_b_threshold', models.IntegerField(default=70)),
                ('grade_c_threshold', models.IntegerField(default=60)),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_group', models.BooleanField(default=False)),
                ('min_members', models.PositiveIntegerField(default=1)),
                ('max_members', models.PositiveIntegerField(default=1)),
                ('program_type', models.CharField(choices=[('STAGE', 'Stage Program'), ('OFF_STAGE', 'Off-Stage Program')], default='STAGE', max_length=15)),
                ('presentation_mode', models.CharField(choices=[('SEQUENTIAL', 'Per Participant (Sequential)'), ('SIMULTANEOUS', 'All-at-Once (Simultaneous/Written)')], default='SEQUENTIAL', max_length=15)),
                ('duration_per_participant', models.PositiveIntegerField(default=5, help_text='Duration in minutes')),
                ('buffer_margin_minutes', models.PositiveIntegerField(default=0, help_text='Extra buffer time in minutes')),
                ('is_announced', models.BooleanField(default=False)),
                ('announced_at', models.DateTimeField(blank=True, null=True)),
                ('result_number', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.category')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.competition')),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_letter', models.CharField(blank=True, max_length=5, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('points_awarded', models.BooleanField(default=False)),
                ('marks_added_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.contestant')),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_participations', to='core.program')),
            ],
            options={
                'ordering': ['program', 'rank', '-marks'],
            },
        ),
        migrations.CreateModel(
            name='GroupParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=150)),
                ('code_letter', models.CharField(blank=True, max_length=5, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('points_awarded', models.BooleanField(default=False)),
                ('marks_added_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_groups', to='core.contestant')),
                ('contestants', models.ManyToManyField(related_name='group_entries', to='core.contestant')),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_participations', to='core.program')),
            ],
            options={
                'ordering': ['program', 'rank', '-marks'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage_type', models.CharField(choices=[('STAGE', 'Stage Venue'), ('OFF_STAGE', 'Off-Stage Venue')], default='STAGE', max_length=15)),
                ('location_details', models.CharField(blank=True, max_length=200)),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
            options={
                'ordering': ['stage_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_duration_minutes', models.PositiveIntegerField(default=0)),
                ('fest_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.festday')),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.program')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.stage')),
            ],
            options={
                'ordering': ['fest_day__day_number', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='preferred_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_programs', to='core.stage'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_letter', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('total_points', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.competition')),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
            options={
                'ordering': ['-total_points', 'name'],
            },
        ),
    ]
