# Generated by Django 5.2.4 on 2026-08-02 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_participations', to='core.team'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='core.team'),
        ),
        migrations.AlterUniqueTogether(
            name='festday',
            unique_together={('competition', 'day_number')},
        ),
        migrations.AlterUniqueTogether(
            name='pointsconfig',
            unique_together={('institution',)},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('program', 'contestant')},
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together={('institution', 'competition', 'chest_no')},
        ),
    ]
