# Generated by Django 5.2.4 on 2026-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='included_categories',
            field=models.ManyToManyField(blank=True, help_text='Included base categories for this common category', related_name='parent_common_categories', to='core.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_common',
            field=models.BooleanField(default=False, help_text='True if this is a combined/common category containing multiple base categories'),
        ),
    ]
