# Generated by Django 5.2.4 on 2026-08-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_start_chest_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Optional WhatsApp contact number', max_length=20, null=True),
        ),
    ]
