# Generated by Django 5.2.4 on 2026-08-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contestant_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='reserved_days',
            field=models.ManyToManyField(blank=True, help_text='Fest days this stage is active/reserved for', related_name='reserved_stages', to='core.festday'),
        ),
    ]
