# Generated by Django 5.2.4 on 2026-08-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stage_reserved_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupparticipation',
            name='judge_marks',
            field=models.JSONField(blank=True, default=dict, help_text="Individual marks per judge e.g. {'1': 85, '2': 90}", null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='judge_marks',
            field=models.JSONField(blank=True, default=dict, help_text="Individual marks per judge e.g. {'1': 85, '2': 90}", null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='judge_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of judges evaluating this program'),
        ),
        migrations.AddField(
            model_name='program',
            name='max_marks_per_judge',
            field=models.PositiveIntegerField(default=100, help_text='Maximum marks allowed per judge'),
        ),
    ]
