# Generated by Django 5.2.4 on 2026-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_program_result_number_program_mark_entry_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional program logo or icon image', null=True, upload_to='program_logos/'),
        ),
    ]
