# Generated by Django 5.2.4 on 2026-08-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_program_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional Fest / Competition Logo', null=True, upload_to='fest_logos/'),
        ),
    ]
