# Generated by Django 5.2.4 on 2026-08-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_competition_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='logo',
        ),
    ]
