# Generated by Django 5.2.4 on 2026-08-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_program_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='name_image',
            field=models.ImageField(blank=True, help_text='Optional custom typography PNG image for the Fest Name', null=True, upload_to='fest_name_images/'),
        ),
    ]
