# Generated by Django 5.2.4 on 2026-08-28 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_competition_custom_result_template'),
        ('tenants', '0007_addon_grantedaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomResultTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Custom Poster', max_length=100)),
                ('image', models.ImageField(upload_to='result_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_poster_templates', to='core.competition')),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
