# Generated by Django 5.2.4 on 2026-09-01 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_populate_announced_result_numbers'),
        ('tenants', '0009_institution_is_public_suspended'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('code', 'Built-in Code Design'), ('custom', 'User Uploaded Template')], default='code', max_length=20)),
                ('template_image', models.ImageField(blank=True, help_text='Custom background certificate template image', null=True, upload_to='certificate_templates/')),
                ('title', models.CharField(default='CERTIFICATE OF MERIT', help_text='Main Certificate Title', max_length=150)),
                ('subtitle', models.CharField(default='PROUDLY PRESENTED TO', help_text='Certificate Subtitle / Award text', max_length=255)),
                ('paragraph_template', models.TextField(blank=True, default='In recognition of outstanding performance and securing {rank_display} ({grade_display}) in {program_name} ({category_name}) at {institution_name} during {fest_name} {fest_year}.', help_text='Customizable citation text with placeholders: {rank_display}, {grade_display}, {program_name}, {category_name}, {institution_name}, {fest_name}, {fest_year}')),
                ('signatory_1_title', models.CharField(default='Co-ordinator', help_text='Left signatory title', max_length=100)),
                ('signatory_1_name', models.CharField(blank=True, default='', help_text='Left signatory name', max_length=100)),
                ('signatory_1_signature', models.ImageField(blank=True, help_text='Optional left signature PNG', null=True, upload_to='signatures/')),
                ('signatory_2_title', models.CharField(default='Principal / Convener', help_text='Right signatory title', max_length=100)),
                ('signatory_2_name', models.CharField(blank=True, default='', help_text='Right signatory name', max_length=100)),
                ('signatory_2_signature', models.ImageField(blank=True, help_text='Optional right signature PNG', null=True, upload_to='signatures/')),
                ('issue_date', models.DateField(blank=True, help_text='Date of Certificate Issue', null=True)),
                ('custom_text_offset_top', models.PositiveIntegerField(default=35, help_text='Vertical start offset in % for custom template text overlay')),
                ('include_places', models.CharField(default='1,2,3', help_text='Comma-separated ranks to include, e.g. 1,2,3', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_configs', to='core.competition')),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
