# Generated by Django 5.2.4 on 2026-09-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_certificateconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_group_programs_per_contestant',
            field=models.PositiveIntegerField(default=0, help_text='Maximum group programs allowed per contestant (0 for no limit / unlimited)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='max_single_programs_per_contestant',
            field=models.PositiveIntegerField(default=0, help_text='Maximum single programs allowed per contestant (0 for no limit / unlimited)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='max_total_programs_per_contestant',
            field=models.PositiveIntegerField(default=0, help_text='Maximum total programs allowed per contestant (0 for no limit / unlimited)'),
        ),
    ]
