# Generated by Django 5.2.4 on 2026-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_competition_max_group_programs_per_contestant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_participants_per_team_per_program',
            field=models.PositiveIntegerField(default=0, help_text='Default maximum participants allowed per team in a program (0 for no limit / unlimited)'),
        ),
        migrations.AddField(
            model_name='program',
            name='max_participants_per_team',
            field=models.PositiveIntegerField(default=0, help_text='Maximum participants allowed per team for this program (0 to use fest default / unlimited)'),
        ),
    ]
