# Generated by Django 5.2.4 on 2026-09-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_competition_max_participants_per_team_per_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='max_participants_per_team_per_program',
        ),
        migrations.AddField(
            model_name='competition',
            name='max_team_entries_per_group_program',
            field=models.PositiveIntegerField(default=0, help_text='Default maximum group entries allowed per team in a group program (0 for no limit / unlimited)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='max_team_participants_per_single_program',
            field=models.PositiveIntegerField(default=0, help_text='Default maximum participants allowed per team in a single program (0 for no limit / unlimited)'),
        ),
    ]
