# Generated by Django 5.2.4 on 2026-09-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_competition_max_participants_per_team_per_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsconfig',
            name='enable_grades',
            field=models.BooleanField(default=True, help_text='Enable Grades (A+, A, B, C) and display Grade columns across result sheets and scoreboards. Turn OFF for Ranks Only mode.'),
        ),
    ]
