# Generated by Django 5.2.4 on 2026-09-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pointsconfig_enable_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='allow_category_management',
            field=models.BooleanField(default=True, help_text='Allow adding, editing, or deleting Categories'),
        ),
        migrations.AddField(
            model_name='competition',
            name='allow_contestant_registration',
            field=models.BooleanField(default=True, help_text='Allow adding, editing, or deleting Contestants & Bulk Upload'),
        ),
        migrations.AddField(
            model_name='competition',
            name='allow_program_assignment',
            field=models.BooleanField(default=True, help_text='Allow assigning or unassigning contestants in single and group programs'),
        ),
        migrations.AddField(
            model_name='competition',
            name='allow_program_management',
            field=models.BooleanField(default=True, help_text='Allow adding, editing, or deleting Programs & Bulk Import'),
        ),
        migrations.AddField(
            model_name='competition',
            name='allow_team_management',
            field=models.BooleanField(default=True, help_text='Allow adding, editing, or deleting Teams'),
        ),
    ]
