# Generated by Django 5.2.4 on 2026-09-04 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_competition_allow_category_management_and_more'),
        ('tenants', '0010_addonrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramResultEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, default='Marks/Results updated', max_length=255)),
                ('changes_summary', models.TextField(blank=True, help_text='Human-readable summary of what changed')),
                ('details', models.JSONField(blank=True, default=list, help_text='Structured list of per-contestant before/after changes')),
                ('snapshot_before', models.JSONField(blank=True, default=dict)),
                ('snapshot_after', models.JSONField(blank=True, default=dict)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_edits', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='core.program')),
            ],
            options={
                'verbose_name': 'Program Result Edit History',
                'verbose_name_plural': 'Program Result Edit Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
