# Generated by Django 5.2.4 on 2026-09-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reorder_announced_result_numbers'),
        ('tenants', '0010_addonrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom', models.BooleanField(default=False, help_text='Set to True if this program has custom scoring rules')),
                ('enable_grades', models.BooleanField(default=True, help_text='Enable Grades for this specific program')),
                ('rank_1_points', models.IntegerField(default=5)),
                ('rank_2_points', models.IntegerField(default=3)),
                ('rank_3_points', models.IntegerField(default=1)),
                ('grade_aplus_points', models.IntegerField(default=6)),
                ('grade_a_points', models.IntegerField(default=5)),
                ('grade_b_points', models.IntegerField(default=3)),
                ('grade_c_points', models.IntegerField(default=1)),
                ('grade_aplus_threshold', models.IntegerField(default=90)),
                ('grade_a_threshold', models.IntegerField(default=80)),
                ('grade_b_threshold', models.IntegerField(default=70)),
                ('grade_c_threshold', models.IntegerField(default=60)),
                ('institution', models.ForeignKey(help_text='Tenant institution scoping', on_delete=django.db.models.deletion.CASCADE, to='tenants.institution')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_points_config', to='core.program')),
            ],
            options={
                'verbose_name': 'Program Points Configuration',
                'verbose_name_plural': 'Program Points Configurations',
            },
        ),
    ]
