# Generated by Django 5.2.4 on 2026-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_programpointsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupparticipation',
            name='prize_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='prize_distributed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupparticipation',
            name='prize_distributed_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='participation',
            name='prize_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participation',
            name='prize_distributed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='prize_distributed_notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pointsconfig',
            name='prize_rank_limit',
            field=models.PositiveIntegerField(default=3, help_text='Default rank cutoff for prize distribution (e.g. 1 for 1st only, 2 for 1st & 2nd, 3 for 1st, 2nd & 3rd)'),
        ),
    ]
