# Generated by Django 5.2.4 on 2026-08-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsubscription',
            name='additional_work_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='institutionsubscription',
            name='additional_work_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionapplication',
            name='additional_requirements',
            field=models.TextField(blank=True, help_text='Custom feature requests or additional needs'),
        ),
        migrations.AddField(
            model_name='subscriptionapplication',
            name='additional_work_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Developer custom charge for additional work', max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=3000.0, help_text='Original regular plan price before discount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=999.0, help_text='Offer plan price', max_digits=10),
        ),
    ]
