# Generated by Django 5.2.4 on 2026-08-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_institutionsubscription_additional_work_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description_ml',
            field=models.TextField(blank=True, help_text='Malayalam description for the plan'),
        ),
    ]
