# Generated by Django 5.2.4 on 2026-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_subscriptionplan_description_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionapplication',
            name='payment_utr',
            field=models.CharField(blank=True, help_text='UPI Payment UTR / Transaction Reference ID', max_length=100),
        ),
    ]
