# Generated by Django 5.2.4 on 2026-08-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_subscriptionapplication_payment_utr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Payment Pending (Step 1 Complete)'), ('PENDING', 'Pending Developer Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15),
        ),
    ]
