# Generated by Django 5.2.4 on 2026-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_subscriptionapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='demo_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration date for Demo Trial', null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Is this institution in 5-Day Demo/Trial mode?'),
        ),
        migrations.AddField(
            model_name='subscriptionapplication',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Application requested 5-Day Free Demo mode'),
        ),
    ]
