# Generated by Django 5.2.4 on 2026-08-07 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_institution_demo_expires_at_institution_is_demo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add-on Name (e.g. Contestant User Creation)', max_length=150)),
                ('code', models.SlugField(help_text='Unique Identifier Code (e.g. contestant-user-creation)', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price for this add-on', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrantedAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, help_text='Optional developer note or custom pricing info', max_length=255)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='tenants.addon')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_add_ons', to='tenants.institution')),
            ],
            options={
                'unique_together': {('institution', 'add_on')},
            },
        ),
    ]
