# Generated by Django 5.2.4 on 2026-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_addon_grantedaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='allow_developer_access',
            field=models.BooleanField(default=False, help_text="Allow Developer/Superadmin support access to this institution's workspace"),
        ),
    ]
