# Generated by Django 5.2.4 on 2026-09-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_institution_allow_developer_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_public_suspended',
            field=models.BooleanField(default=False, help_text='Suspend public live portal link for this institution'),
        ),
    ]
