# Generated by Django 5.2.4 on 2026-09-01 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_institution_is_public_suspended'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved / Granted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tenants.addon')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_requests', to='tenants.institution')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
