# Generated by Django 5.2.4 on 2026-08-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_start_chest_no'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_competitions',
            field=models.ManyToManyField(blank=True, help_text='Competitions fixed/assigned to this judge', related_name='assigned_judges', to='core.competition'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_programs',
            field=models.ManyToManyField(blank=True, help_text='Specific programs assigned to this judge', related_name='assigned_judges', to='core.program'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer / Super Admin'), ('INSTITUTION_ADMIN', 'Institution Admin'), ('SUB_ADMIN', 'Sub-Admin / Coordinator'), ('TABULATOR', 'Tabulator / Mark Entry Officer'), ('JUDGE', 'Judge / Evaluator'), ('TEAM_LEADER', 'Team Leader / Manager')], default='TEAM_LEADER', max_length=20),
        ),
    ]
