# Generated by Django 5.2.4 on 2026-08-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_start_chest_no'),
        ('users', '0002_user_assigned_competitions_user_assigned_programs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contestant',
            field=models.OneToOneField(blank=True, help_text='Linked contestant record for Contestant role', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='core.contestant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Developer / Super Admin'), ('INSTITUTION_ADMIN', 'Institution Admin'), ('SUB_ADMIN', 'Sub-Admin / Coordinator'), ('TABULATOR', 'Tabulator / Mark Entry Officer'), ('JUDGE', 'Judge / Evaluator'), ('TEAM_LEADER', 'Team Leader / Manager'), ('CONTESTANT', 'Contestant Pupil')], default='TEAM_LEADER', max_length=20),
        ),
    ]
